# Generated by Django 5.0.4 on 2024-05-06 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=30)),
                ('description', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('vat', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'places',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('category', models.JSONField()),
                ('discounts', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonAlias',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='aliases', to='registry.person')),
            ],
            options={
                'verbose_name_plural': 'aliases',
            },
        ),
        migrations.CreateModel(
            name='PortfolioAlias',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('portofolio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='aliases', to='registry.portfolio')),
            ],
            options={
                'verbose_name_plural': 'aliases',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='registry.billing')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='registry.membershiptype')),
                ('of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registry.personalias')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='members', to='registry.plan')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='registry.portfolioalias')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('in_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_places', to='registry.person', verbose_name='in')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.place')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='registry.roletype')),
            ],
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('in_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_persons', to='registry.person', verbose_name='in')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='registry.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='registry.roletype')),
            ],
        ),
    ]
