# Generated by Django 5.0.4 on 2024-05-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioalias',
            old_name='portofolio',
            new_name='portfolio',
        ),
    ]
