# Generated by Django 5.0.4 on 2024-05-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_rename_portofolio_portfolioalias_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='unit',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
