# Generated by Django 5.0.4 on 2024-05-06 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_plan_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
