# Generated by Django 5.0.4 on 2024-05-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_plan_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
            ],
        ),
    ]
