# Generated by Django 5.0.4 on 2024-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_sshrootca_alter_billing_id_alter_person_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshrootca',
            name='last_serial',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
