# Generated by Django 5.0.4 on 2024-06-12 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_sshrootca_last_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='head_quarter',
        ),
        migrations.AddField(
            model_name='customer',
            name='bu_place',
            field=models.ForeignKey(blank=True, help_text='operative office', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='registry.place'),
        ),
        migrations.AddField(
            model_name='customer',
            name='engineering_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='registry.person'),
        ),
        migrations.AddField(
            model_name='customer',
            name='hq_place',
            field=models.ForeignKey(blank=True, help_text='* head office', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='registry.place'),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='registry.person'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purchase_manager',
            field=models.ForeignKey(blank=True, help_text='* person who has to sign commercial offer', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='registry.person'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='team_leader',
            field=models.ForeignKey(blank=True, help_text='* person who has to sign technical offer', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='registry.person'),
        ),
    ]
