# Generated by Django 5.0.4 on 2024-06-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_remove_customer_head_quarter_customer_bu_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='of',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registry.customer'),
        ),
        migrations.RemoveField(
            model_name='personrole',
            name='in_person',
        ),
        migrations.RemoveField(
            model_name='personrole',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='placerole',
            name='in_person',
        ),
        migrations.RemoveField(
            model_name='placerole',
            name='place',
        ),
        migrations.RemoveField(
            model_name='placerole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='portfolioalias',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='membership',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='registry.portfolio'),
        ),
        migrations.DeleteModel(
            name='PersonAlias',
        ),
        migrations.DeleteModel(
            name='PersonRole',
        ),
        migrations.DeleteModel(
            name='PlaceRole',
        ),
        migrations.DeleteModel(
            name='RoleType',
        ),
        migrations.DeleteModel(
            name='PortfolioAlias',
        ),
    ]
