# Generated by Django 5.0.4 on 2024-06-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_alter_company_options_alter_customer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='vat',
        ),
    ]
