# Generated by Django 5.0.4 on 2024-06-14 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_sshrootca'),
        ('registry', '0012_remove_person_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='certificate',
        ),
        migrations.AddField(
            model_name='project',
            name='ca_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.sshrootca'),
        ),
        migrations.DeleteModel(
            name='SSHRootCA',
        ),
    ]
