# Generated by Django 5.1.2 on 2024-11-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_customer_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='delivery_download_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='delivery_last_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='delivery_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='external_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='external_ref_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='last_build_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='last_build_outcome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='last_build_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='last_build_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='last_build_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='production_download_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='production_last_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='production_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='source_code_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='staging_download_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='staging_last_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='staging_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
