# Generated by Django 5.1.2 on 2024-11-12 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_deliverable_delivery_download_uri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=30)),
                ('stage', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('source_code_uri', models.URLField(blank=True, null=True)),
                ('external_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('external_ref_uri', models.URLField(blank=True, null=True)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='registry.deliverable')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
