# Generated by Django 5.1.2 on 2024-11-12 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_deliverableevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('delivery', 'Delivery')], max_length=20)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('download_uri', models.URLField(blank=True, null=True)),
                ('current_configuration_uri', models.URLField(blank=True, null=True)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='registry.deliverable')),
            ],
            options={
                'unique_together': {('deliverable', 'stage')},
            },
        ),
    ]
