# Generated by Django 5.1.2 on 2024-11-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_deliverableconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverableconfiguration',
            name='stage',
            field=models.CharField(max_length=20),
        ),
    ]
