# Generated by Django 5.1.2 on 2024-11-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_alter_deliverableconfiguration_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='delivery_download_uri',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='delivery_last_published_at',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='delivery_version',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='production_download_uri',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='production_last_published_at',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='production_version',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='staging_download_uri',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='staging_last_published_at',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='staging_version',
        ),
        migrations.AlterField(
            model_name='deliverableconfiguration',
            name='stage',
            field=models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('delivery', 'Delivery')], max_length=20),
        ),
    ]
