# Generated by Django 5.1.2 on 2024-11-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_remove_deliverable_delivery_download_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='delivery_download_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='delivery_last_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='delivery_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='production_download_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='production_last_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='production_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='staging_download_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='staging_last_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='staging_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliverableconfiguration',
            name='stage',
            field=models.CharField(max_length=20),
        ),
    ]
