# Generated by Django 5.1.2 on 2024-11-12 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_remove_deliverableevent_deliverable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='registry.project'),
        ),
    ]
