# Generated by Django 5.1.2 on 2024-11-12 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_alter_deliverable_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('outcome', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('source_code_uri', models.URLField()),
                ('external_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('external_ref_uri', models.URLField(blank=True, null=True)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='registry.deliverable')),
            ],
        ),
    ]
