# Generated by Django 5.1.2 on 2024-11-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='stage_status',
            field=models.JSONField(default=dict),
        ),
    ]
